### ISSUE TITLE
Failed to read skill package schema due to SyntaxError: Unexpected token < in JSON at position 0, the skill package watcher won't start.

### ISSUE THREAD

**Issue by digitaltoast** [alexa/ask-toolkit-for-vscode#86] opened 2021-01-21 15:33 UTC
**Describe the bug**

Skill just updated to 2.3.0 and now I'm getting warnings in the alert window of VSCode:

> Failed to read skill package schema due to SyntaxError: Unexpected token < in JSON at position 0, the skill package watcher won't start. 

**Extension Logs**

```
[info - 2021-01-21 15:30:04.381Z] Activating extension 
[debug - 2021-01-21 15:30:04.382Z] Registering commands in the extension 
[debug - 2021-01-21 15:30:04.384Z] Registering views in the extension 
[debug - 2021-01-21 15:30:04.397Z] Calling method: ask.welcome 
[debug - 2021-01-21 15:30:04.398Z] Calling method: welcomeScreen.getHtmlForView 
[verbose - 2021-01-21 15:30:04.398Z] Calling method: checkGitInstallation 
[verbose - 2021-01-21 15:30:04.398Z] Calling method: isGitInstalled 
[verbose - 2021-01-21 15:30:04.398Z] Executing git command : git --version 
[debug - 2021-01-21 15:30:04.406Z] Calling method: renderView, args:  [{"name":"welcomeScreen","js":false,"args":{"enabled":"checked"}}]
[debug - 2021-01-21 15:30:04.406Z] Calling method: interpolate, args:  [{"enabled":"checked"}]
[debug - 2021-01-21 15:30:04.408Z] Registering event handlers in the extension 
[debug - 2021-01-21 15:30:04.409Z] Registering statusbar in the extension 
[verbose - 2021-01-21 15:30:04.409Z] Updating profile icon in the extension 
[debug - 2021-01-21 15:30:04.409Z] Registering treeviews in the extension 
[verbose - 2021-01-21 15:30:04.414Z] Calling method: findSkillFolders 
[debug - 2021-01-21 15:30:04.610Z] Calling method: welcomeScreen.onViewChangeListener 
[verbose - 2021-01-21 15:30:05.113Z] Calling method: getOrInstantiateGitApi 
[verbose - 2021-01-21 15:30:05.116Z] Calling method: findSkillFolders 
[debug - 2021-01-21 15:30:05.117Z] Checking if extension version is latest 
[debug - 2021-01-21 15:30:06.565Z] Successfully uploaded telemetry data. 
[info - 2021-01-21 15:30:09.947Z] skill package schema has been updated. 
[debug - 2021-01-21 15:30:09.948Z] Failed to read skill package schema due to SyntaxError: Unexpected token < in JSON at position 0, the skill package watcher won't start. 
[verbose - 2021-01-21 15:30:09.948Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-01-21 15:30:09.949Z] Calling method: getAskResourceConfig 
[info - 2021-01-21 15:30:09.949Z] SkillPackageWatcher is started 
[info - 2021-01-21 15:30:04.381Z] Activating extension 
[debug - 2021-01-21 15:30:04.382Z] Registering commands in the extension 
[debug - 2021-01-21 15:30:04.384Z] Registering views in the extension 
[debug - 2021-01-21 15:30:04.397Z] Calling method: ask.welcome 
[debug - 2021-01-21 15:30:04.398Z] Calling method: welcomeScreen.getHtmlForView 
[verbose - 2021-01-21 15:30:04.398Z] Calling method: checkGitInstallation 
[verbose - 2021-01-21 15:30:04.398Z] Calling method: isGitInstalled 
[verbose - 2021-01-21 15:30:04.398Z] Executing git command : git --version 
[debug - 2021-01-21 15:30:04.406Z] Calling method: renderView, args:  [{"name":"welcomeScreen","js":false,"args":{"enabled":"checked"}}]
[debug - 2021-01-21 15:30:04.406Z] Calling method: interpolate, args:  [{"enabled":"checked"}]
[debug - 2021-01-21 15:30:04.408Z] Registering event handlers in the extension 
[debug - 2021-01-21 15:30:04.409Z] Registering statusbar in the extension 
[verbose - 2021-01-21 15:30:04.409Z] Updating profile icon in the extension 
[debug - 2021-01-21 15:30:04.409Z] Registering treeviews in the extension 
[verbose - 2021-01-21 15:30:04.414Z] Calling method: findSkillFolders 
[debug - 2021-01-21 15:30:04.610Z] Calling method: welcomeScreen.onViewChangeListener 
[verbose - 2021-01-21 15:30:05.113Z] Calling method: getOrInstantiateGitApi 
[verbose - 2021-01-21 15:30:05.116Z] Calling method: findSkillFolders 
[debug - 2021-01-21 15:30:05.117Z] Checking if extension version is latest 
[debug - 2021-01-21 15:30:06.565Z] Successfully uploaded telemetry data. 
[info - 2021-01-21 15:30:09.947Z] skill package schema has been updated. 
[debug - 2021-01-21 15:30:09.948Z] Failed to read skill package schema due to SyntaxError: Unexpected token < in JSON at position 0, the skill package watcher won't start. 
[verbose - 2021-01-21 15:30:09.948Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-01-21 15:30:09.949Z] Calling method: getAskResourceConfig 
[info - 2021-01-21 15:30:09.949Z] SkillPackageWatcher is started 
```

**Desktop (please complete the following information):**

-   OS: Win 10 Pro X64 /  Ubuntu 20.04 (remote) 
-   Visual Studio Code Version: 1.52.1
-   Alexa Skill Toolkit Version: 2.3.0

**Additional context**

This happens as soon as I load the remote host - I do not have an Alexa skill open and I am not in an Alexa skill folder. Have tried uninstalling and re-installing extension. v2.2.0 is OK v 2.3.0 pops up the error.

Thanks

**Comment by Chih-Ying** [comment] 2021-01-21 17:56
Hi @digitaltoast,

Thank you for the report. 

It looks like the skill package schema has been downloaded successfully, but the program failed at reading the schema file. We believe the downloaded schema might contain a wrong format. Therefore, could you share with us your skill package schema. It is locaed at this directory `your_skill_folder/.ask/schema/skillPackageSchema.json`? 

Thank you.

**Comment by digitaltoast** [comment] 2021-01-21 19:07
Hi there; no idea what skill this would be. I do not have any skills open or loaded, or any folders open.
I have lots of skills in various states, but I have no idea which the extension is looking at as none is open or loaded.

**Comment by ShenChen-Amazon** [comment] 2021-01-21 20:37
Hi @digitaltoast ,

We just fixed an issue on service side which will block the extension to download the skillPackage schema. I am not sure if it is the root cause of your issue. Could you please try and let us know if you still see the error message ?

Thanks,
Shen

**Comment by digitaltoast** [comment] 2021-01-21 23:03
Hi there - yes! No changes at my end, but I just tried again and the error is gone! Thanks

**Comment by ShenChen-Amazon** [comment] 2021-01-21 23:08
Hi @digitaltoast ,

Glad to hear that the fix works for you :) Thanks a again for using our latest toolkit package and posting this issue. Closing this issue now.

Thanks,
Shen

**Closed by ShenChen-Amazon** 2021-01-21 23:08 UTC
Labels: bug
