### ISSUE TITLE
Unable to download files on local machine

### ISSUE THREAD

**Issue by khac** [alexa/ask-toolkit-for-vscode#59] opened 2020-11-12 17:53 UTC
Unable to Download and edit skill on VS Code

When I open the ASK Toolkit and Create `Alexa-hosted skill` I can see the change in the developer console, but I am unable to get the files downloaded locally on the machine.

The error message I get is 
```
Skill creation failed. Reason: Git folder setup failed for /Users/a/Desktop/AlexaSkills/hello123. Reason: Failed to execute git {
  "exitCode": 1,
  "gitCommand": "checkout",
  "stdout": "",
  "stderr": "error: pathspec 'prod' did not match any file(s) known to git\n"
}
```

I believe the error is because I am currently not in sync with the Amazon developer console.

**Comment by nikhilym** [comment] 2020-11-12 18:36
@khac , thanks for logging the bug. This seems to be similar to the bug #54 . We figured the issue is with respect to a bug in our clone skill functionality and fixed it through the PR #56 . However, that fix has not been released in the extension.

Sorry for the inconvenience. We will be working on releasing the patch soon. 

In the mean time, to get around this, you can manually install the earlier version of the toolkit from the marketplace and try creating/downloading the skills. Once downloaded, for using the latest toolkit features you can upgrade it back to the latest version. We understand this is painful, is not the best developer experience and will try to address this through our next release ASAP.

**Comment by khac** [comment] 2020-11-12 20:42
@nikhilym I installed an older version, v2.0.2
The error was the same, when I tried to Create Alexa-hosted skill, at the same time, I was able to see the skill being created on the Alexa developer console.
```
Skill creation failed. Reason: Git folder setup failed for /Users/adit/Desktop/AlexaSkills/qwer123. Reason: Failed to execute git { "exitCode": 1, "gitCommand": "checkout", "stdout": "", "stderr": "error: pathspec 'prod' did not match any file(s) known to git\n" }
```

1. Could you suggest a way to download the code from the Alexa Developer Console?
2. Also, I was wondering how to sync with the Amazon Developer Console `git` so that I can view the code there as well.

**Comment by nikhilym** [comment] 2020-11-13 01:28
Interesting. I was not able to reproduce this error. Can you please provide some more details about your toolkit configuration? Please run `Alexa: About Alexa Skill Toolkit` command from command palette, and paste that information here. For context, here is my toolkit configuration : 

````
OS: Darwin x64 19.6.0
Visual Studio Code Version:  1.51.1
Alexa Skills Toolkit Version: 2.1.0
Git Version: git version 2.29.2
````

Also, can you try downloading the skill and see if the issue persists? Is it happening for an existing skill as well or only for a new skill?

**Comment by SpellMender** [comment] 2020-11-13 18:33
Any news on the update? I'm having the same problem.

**Comment by SpellMender** [comment] 2020-11-13 18:46
@nikhilym here is what shows up when I run `Alexa: About Alexa Skill Toolkit`
![alexa](https://user-images.githubusercontent.com/18728350/99109285-cf23e600-25a5-11eb-95e2-d27bba961df6.png)

**Comment by Chih-Ying** [comment] 2020-11-13 19:28
@SpellMender @khac Thanks for reporting. 
Are you able to `ask fetch`, `ask checkout prod` and `ask checkout master` in the project root directory using the command line?

**Comment by khac** [comment] 2020-11-13 23:09
@nikhilym 
OS: Darwin x64 19.6.0
Visual Studio Code Version:  1.51.1
Alexa Skills Toolkit Version: 2.1.0
Git Version: git version 2.28.0

@Chih-Ying 
My git is connected to my github.com account not the Alexa or AWS account, I was able to download the files from `Amazon Developer Console`

**Comment by coolbigbear** [comment] 2020-11-13 23:37
Having the same issue. 
`OS: Windows_NT x64 10.0.19042
Visual Studio Code Version:  1.51.1
Alexa Skills Toolkit Version: 2.1.0
Git Version: git version 2.23.0.windows.1`

Clicking on `Download and edit skill` also does nothing.
Error:
`Skill creation failed. Reason: Git folder setup failed for ...\AlexaSkills\test-test\test-test. Reason: Failed to execute git { "exitCode": 128, "gitErrorCode": "AuthenticationFailed", "gitCommand": "fetch", "stdout": "", "stderr": "...\.ask\\scripts\\git-credential-helper: line 11: ${configFile}: ambiguous redirect\n ...\.ask\\scripts\\git-credential-helper: line 11: ${configFile}: ambiguous redirect\nfatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/8b1aa862-0611-47fa-80bf-f6c054a0828c/'\n" }`

I can execute `git fetch` just fine

**Comment by Chih-Ying** [comment] 2020-11-14 00:21
> @nikhilym @Chih-Ying
> OS: Darwin x64 19.6.0
> Visual Studio Code Version: 1.51.1
> Alexa Skills Toolkit Version: 2.1.0
> Git Version: git version 2.28.0
> 
> My git is connected to my github.com account, not the Alexa or AWS account, I was able to download the files from `Amazon Developer Console`
> 
> * Kindly let me know how to connect again to the git repository on the cloud to run the git commands.


@khac  The ASK Toolkit extension automatically initializes git and configure git credentials for users, so users to access the AWS CodeCommit repository that the hosted skill resides at. This git is using different account from your personal git account.

More information you can look into [FAQs:Why do I get a prompt for Git credentials when an Alexa hosted skill is created or downloaded? ](https://github.com/alexa/ask-toolkit-for-vscode#faqs)

So you were able to download the same skill as before?

Can you successfully run `git fetch`, `git checkout prod` and `git checkout master` without error messages?

**Comment by Chih-Ying** [comment] 2020-11-14 02:57
> Having the same issue.
> `OS: Windows_NT x64 10.0.19042 Visual Studio Code Version: 1.51.1 Alexa Skills Toolkit Version: 2.1.0 Git Version: git version 2.23.0.windows.1`
> 
> Clicking on `Download and edit skill` also does nothing.
> Error:
> `Skill creation failed. Reason: Git folder setup failed for ...\AlexaSkills\test-test\test-test. Reason: Failed to execute git { "exitCode": 128, "gitErrorCode": "AuthenticationFailed", "gitCommand": "fetch", "stdout": "", "stderr": "...\.ask\\scripts\\git-credential-helper: line 11: ${configFile}: ambiguous redirect\n ...\.ask\\scripts\\git-credential-helper: line 11: ${configFile}: ambiguous redirect\nfatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/8b1aa862-0611-47fa-80bf-f6c054a0828c/'\n" }`
> 
> I can execute `git fetch` just fine

**Comment by Chih-Ying** [comment] 2020-11-14 03:08
@khac  @SpellMender  @coolbigbear 
We observed the `Download and edit skill` does not work in the latest Visual Studio Code(version 1.51). We are currently investigating.

To unblock your work, please downgrade your [Visual Studio Code to 1.50 <=  ](https://code.visualstudio.com/updates/v1_50) , Please let us know if skill creation and downloading still do not work.

**Comment by coolbigbear** [comment] 2020-11-14 15:41
Downgrading to 1.49.3 does make `Download and edit skill` button work. 
However, it fails later with the same issue I mentioned (`Skill creation failed. Reason: Git folder setup failed for`), `git fetch` also did not work this time.

I managed to fix it by simply adding quotes around `${configFile}` inside the `git-credential-helper`.
Specifically:
1. Opened  `git-credential-helper` in notepad. For me located in `C:\Users\<user_name>\.ask\scripts`
2. Changed the `${configFile}` on this line `askRefreshToken=$(tr -d '\n' <  ${configFile} | tr -d ' ' | sed -n $configOp | sed 's/".*//')` to be surrounded by quotes i.e. `"${configFile}"`
3. `git fetch` worked fine in the directory now and using `Download and edit skill` while on VSCode version = 1.49.3 works.

**Comment by coolbigbear** [comment] 2020-11-14 15:47
> Downgrading to 1.49.3 does make `Download and edit skill` button work.
> However, it fails later with the same issue I mentioned (`Skill creation failed. Reason: Git folder setup failed for`), `git fetch` also did not work this time.
> 
> I managed to fix it by simply adding quotes around `${configFile}` inside the `git-credential-helper`.
> Specifically:
> 
> 1. Opened  `git-credential-helper` in notepad. For me located in `C:\Users\<user_name>\.ask\scripts`
> 2. Changed the `${configFile}` on this line `askRefreshToken=$(tr -d '\n' <  ${configFile} | tr -d ' ' | sed -n $configOp | sed 's/".*//')` to be surrounded by quotes i.e. `"${configFile}"`
> 3. `git fetch` worked fine in the directory now and using `Download and edit skill` while on VSCode version = 1.49.3 works.

Pushing updates failed due to the same error but in `ask-pre-push` script inside the same directory.
Identical fix worked

**Comment by SpellMender** [comment] 2020-11-14 17:20
@Chih-Ying

When I run `git fetch`:
![image](https://user-images.githubusercontent.com/18728350/99152997-c1806600-2662-11eb-8d1c-244be0c93f96.png)

When I run `git checkout prod`:
![image](https://user-images.githubusercontent.com/18728350/99153017-e7a60600-2662-11eb-8723-0246ce3e2d19.png)

When I run `git checkout master`:
![image](https://user-images.githubusercontent.com/18728350/99153023-fa203f80-2662-11eb-9860-40676947e1e4.png)

**Comment by Chih-Ying** [comment] 2020-11-14 18:02
> > Downgrading to 1.49.3 does make `Download and edit skill` button work.
> > However, it fails later with the same issue I mentioned (`Skill creation failed. Reason: Git folder setup failed for`), `git fetch` also did not work this time.
> > I managed to fix it by simply adding quotes around `${configFile}` inside the `git-credential-helper`.
> > Specifically:
> > 
> > 1. Opened  `git-credential-helper` in notepad. For me located in `C:\Users\<user_name>\.ask\scripts`
> > 2. Changed the `${configFile}` on this line `askRefreshToken=$(tr -d '\n' <  ${configFile} | tr -d ' ' | sed -n $configOp | sed 's/".*//')` to be surrounded by quotes i.e. `"${configFile}"`
> > 3. `git fetch` worked fine in the directory now and using `Download and edit skill` while on VSCode version = 1.49.3 works.
> 
> Pushing updates failed due to the same error but in `ask-pre-push` script inside the same directory.
> Identical fix worked

@coolbigbear  
It’s nice to hear this solution works for you!

I was thinking about this solution as well, but I could not reproduce it 
on Windows 
```
OS: Windows_NT x64 10.0.17763
Visual Studio Code Version: 1.51.1
Alexa Skills Toolkit Version: 2.1.0
Git Version: 2.23.0.windows.1
```
and Mac
```
OS: Darwin x64 18.7.0
Visual Studio Code Version:  1.51.0
Alexa Skills Toolkit Version: 2.1.0
Git Version: git version 2.28.0
```

@SpellMender 
Thanks for your report.
Could you also try the solution @coolbigbear provided? 

We will consider these environment settings into our test cases.

**Comment by SpellMender** [comment] 2020-11-14 18:43
@Chih-Ying I've already attempted his solution. Unfortunately I can't find the .ask\script folder. In fact, my .ask folder is completely blank. I've tried to create a new skill via ASK, and I've tried to use a current skill. Same issue with both attempts. I will try to roll back the VSCode version to see if that helps, but I have my doubts. @coolbigbear if you have any suggestions to reproduce those results I'd love to hear them.

**Comment by Chih-Ying** [comment] 2020-11-14 19:01
@SpellMender 
According to your `git fetch` error message above, I saw you have the file in `C:\Users\<your_user_name>\.ask\scripts\git-credential-helper`. 
The `.ask` folder is not located at your skill project, but in your system at `C:\Users\<your_user_name>\.ask`.

**Comment by coolbigbear** [comment] 2020-11-14 19:05
@SpellMender Looks like you have the exact same issue as me.
Look in your `C:\Users\Michael Kellet\.ask\scripts` folder, should be located there
You'd also need to fix the `ask-pre-push` script while you're in there to be able to push changes.

**Comment by SpellMender** [comment] 2020-11-14 20:46
Thanks! Sorry for the confusion. I'll try that out and report back.

**Comment by SpellMender** [comment] 2020-11-14 22:36
Excellent! @coolbigbear's solution worked for me! I didn't even have to revert back to a different version of VSCode!

From start to finish, here's the process for me to export a skill from the Amazon Developer Console:
1) From the Alexa Developer Console go to the "Code" tab
![image](https://user-images.githubusercontent.com/18728350/99157933-a0337000-268a-11eb-8847-9cfed745741a.png)
2) Select "Offline Tools" on the toolbar above the code
![image](https://user-images.githubusercontent.com/18728350/99157955-c9ec9700-268a-11eb-9ed3-b1415cfcf2fc.png)
3) Select "Export to VSCode"
![image](https://user-images.githubusercontent.com/18728350/99157967-e8529280-268a-11eb-84f8-7ffeabb2d51a.png)
4) You will be prompted to select a folder to load your project into. You don't have to create a new folder. A folder with the name of your project will be created for you. Then the project will fail with the error `Skill clone failed. Reason: Git folder setup failed`
![image](https://user-images.githubusercontent.com/18728350/99158012-5c8d3600-268b-11eb-892d-1954f692805a.png)
5) Open a new Explorer window and navigate to `C:\Users\<your_user_name>\.ask\scripts\`
![image](https://user-images.githubusercontent.com/18728350/99158044-b261de00-268b-11eb-8609-0eaa1bed6bfd.png)
6) Both of these files need to be edited. Double-click and open with your favorite text editor (in my case it was Notepad++)
![image](https://user-images.githubusercontent.com/18728350/99158073-1ab0bf80-268c-11eb-99b7-e677f858ba81.png)
7) Both of those files have a line beginning with `askRefreshToken=`.
![image](https://user-images.githubusercontent.com/18728350/99158094-68c5c300-268c-11eb-9feb-bae5a5482896.png)
You must add double quotes around `${ConfigFile}` for both files. Be sure to save your changes.
![image](https://user-images.githubusercontent.com/18728350/99158088-59467a00-268c-11eb-8831-5699e2b8e0ba.png)
8) Now navigate back to VSCode and make sure to open the folder with your skill (if its not already opened) in your workspace.
![image](https://user-images.githubusercontent.com/18728350/99158243-0cfc3980-268e-11eb-8423-2c6c1ad61c19.png)
9) Open up a Terminal
![image](https://user-images.githubusercontent.com/18728350/99158269-4b91f400-268e-11eb-865d-9f529ac3a265.png)
10) Type the command `git fetch` and press enter. Type the command `git checkout dev` and press enter.
![image](https://user-images.githubusercontent.com/18728350/99158345-f9050780-268e-11eb-998a-3eb57e5a8b82.png)

You will now see files populate in your workspace:
![image](https://user-images.githubusercontent.com/18728350/99158352-133ee580-268f-11eb-8b02-01c88b0a6d45.png)

I figured if anyone on the internet is as visual a learner as I am, this should be helpful.

I'm hoping there is a quicker, easier resolution found soon.

**Comment by coolbigbear** [comment] 2020-11-14 22:43
@SpellMender Great to hear it worked for you!

**Comment by doctor-iksterog** [comment] 2020-11-17 21:59
well, it seems to work for me when i use the Export to VS Code in Dev Console and that creates the directory and exports and open my skill WITHOUT errors. So i guess i will just stick with that. If i ever have to create a new skill i guess i will have to create it first in dev console then open it up in VS Code.

**Comment by SpellMender** [comment] 2020-11-20 13:45
@Chih-Ying @nikhilym This morning I Exported from the developer console via my laptop on a fresh install of VSCode and everything worked without any errors! Perhaps the issue has been resolved!

**Comment by nikhilym** [comment] 2020-11-20 17:39
@SpellMender @khac @coolbigbear @doctor-iksterog sorry for the late response and thanks for keeping this thread super active and updated on the progress. Special thanks to @coolbigbear & @SpellMender to debug and help us resolve the issue. As a small token of appreciation, we added your github user names in our [`Thank you` section](https://github.com/alexa/ask-toolkit-for-vscode/blob/development/media/toolkitUpdate/toolkitUpdate.html#L68-L77) in the toolkit updates view. Anyone can view the toolkit updates view again, in the extension, by running the `Alexa: Show Toolkit Update notes` command in the vscode command palette.

@Chih-Ying fixed the scripts and released them recently. As @SpellMender observed, the recent extension release `v2.2.0` should have these issues fixed. 

> If i ever have to create a new skill i guess i will have to create it first in dev console then open it up in VS Code.

@doctor-iksterog , we hope the latest extension release fixes this for you. The `create skill` view from the extension should work flawlessly for you now. Sorry for the inconvenience. 

I am going ahead and closing this and #54 issue. Please let us know if you are still facing problems. It would also be great if you can let us know of any feedback, feature requests or issues around the extension. Hope you are finding the extension useful 😄

**Closed by nikhilym** 2020-11-20 17:39 UTC
Labels: Status: In Progress, bug

**Comment by HimanshuPrimo** [comment] 2023-06-27 08:18
I am getting this error while cloning the code from the Alexa Developer console on Ubuntu.

Skill clone failed. Reason: Command failed: git branch --show-current

![image](https://github.com/alexa/ask-toolkit-for-vscode/assets/121434728/3ae618eb-a6ce-4706-895b-c039d118e8bd)

Could anyone please let me what I have to do for fix this issue?
OS- Ubuntu

**Comment by tydonelson** [comment] 2023-06-27 16:43
Hey @HimanshuPrimo , do you have git installed on your machine? Per the [prerequisites here](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/get-started-with-the-ask-toolkit-for-visual-studio-code.html#prerequisites), the ASK VSCode extension requires at least version 2.27 of Git to be installed.

**Comment by HimanshuPrimo** [comment] 2023-06-28 07:17
Hi @tydonelson, 

Thanks for the response. It has been really helpful, and I greatly appreciate it. I had an older version of Git, but the issue has now been resolved.
