### ISSUE TITLE
Skill Build Fails whenever Skill.json include an RENDER_TEMPLATE Interface Type

### ISSUE THREAD

**Issue by tuwallace** [alexa/ask-toolkit-for-vscode#76] opened 2020-12-17 18:08 UTC
When you add an Interfaces type of RENDER_TEMPLATE to your skill.json, commit the changes to the file, then deploy skill, the build fails.   I've tried setting and saving the display option in interfaces for my skill in the Alexa Developer Console, using the Skill manifest to download the revised manifest, but I get the same result.  

**To Reproduce**

- open VS Code with the Ask toolkit for VS Code 
- Create a skill
- Edit the skill.json and add RENDER_TEMPLATE as interfaces type
- Commit your changes and deploy the skill 
- You will see a Skill Build failed in the notification panel

**Comment by ShenChen-Amazon** [comment] 2020-12-18 20:16
Hi @tuwallace ,

Thanks for posting this issue. I could reproduce this issue with the following skill.json
```
{
  "manifest": {
    "apis": {
      "custom": {
        "endpoint": {
          "uri": "arn:aws:lambda:us-east-xxx:Release_0"
        },
        "regions": {
          "NA": {
            "endpoint": {
              "uri": "arn:aws:lambda:us-east-xxx:Release_0"
            }
          }
        },
        "interfaces": [
          {
            "minimumTemplateVersion": "1.0",
            "type": "RENDER_TEMPLATE"
          }
        ]
      }
    },
    "publishingInformation": {
      "locales": {
        "en-US": {
          "name": "interfaceTest"
        }
      }
    }
  }
}
```
I also noticed that when only interface proerty exist without `endpoint` and `regions`, the deploy could succeed. But if all those properties exist, the deploy will fail. Since the actual build logic is executed at service side, we would need to reach out to hosted skill team to figure this issue out. I will post update here when we hear back from the service team, please keep tunned :)

Thanks,
Shen

**Comment by sattpat** [comment] 2021-01-02 06:52
Overriding actions. More details can be found [here](https://github.com/alexa/ask-toolkit-for-vscode/issues/65#issuecomment-753440267)

**Comment by ShenChen-Amazon** [comment] 2021-01-08 23:53
Hi @tuwallace ,

Sorry for responding late. From [the public doc](https://developer.amazon.com/en-US/docs/alexa/custom-skills/display-interface-reference.html), RENDER_TEMPLATE is now deprecated and and isn't supported on all Alexa devices.  Thus I recommend you to switch to use APL as recommended in the doc.

There's a lot of possible issues which will lead to deploy fail. For your case, I guess The root cause is that to enable a render template interface, there are some additional builtIn Intent required in the InteractionModel such as AMAZON.NextIntent. When you enable the render template interface on developer console, you will see a lot Amazon intents are added to your Interaction model. Those Intents are required in your Interaction model when you do the deploy.

I undersand that the current error message from the extension is not helpful, it only tells you the deploy fail without detailed reason. That is becuase there's a some limitation on api side and currently our extension are unable to retrieve detailed error message. This is a known issue and we've already reported to the service side. I am really sorry for the incovenient.

Due to the root cause is from the service side, there's nothing our extension could do to better imporve the user experience at the moment, I  will close this issue from the extension side for now. Please feel free to reopen if you have any questions :) 

Thanks,
Shen

**Closed by ShenChen-Amazon** 2021-01-08 23:53 UTC
Labels: bug, waiting: external dependency
